
(CLEAR-ALL)
(DEFINE-MODEL COMBINED
              (SGP :V
                   T
                   :NEEDS-MOUSE
                   T
                   :SHOW-FOCUS
                   T
                   :ESC
                   T
                   :PROCESS-CURSOR
                   T)
              (SGP :VISUAL-FINST-SPAN 100)
              (SETF VG-GLOMMING-RADIUS 8)
              (SETF VG-COLLISION-TYPE 'BOX)
              (SETF VG-NAMING-TYPE 'SEQUENTIAL)
              (CHUNK-TYPE MAKEVOTE
                          RACE
                          CANDIDATE
                          PARTY
                          BUTTON
                          POSITION
                          SCREEN
                          STATE
                          HANDPOS
                          TO-DO
                          FOUND
                          DEFAULT
                          ENDSTATE
                          LEFT
                          RIGHT)
              (CHUNK-TYPE CANDIDATE NAME PARTY RACE)
              (CHUNK-TYPE VOTEPARTY DEFAULT)
              (CHUNK-TYPE ABSTAIN CONTEST)
              (CHUNK-TYPE VISUALGROUP
                          RACE-GROUP
                          CANDIDATE-GROUP
                          PARTY-GROUP
                          NEXTPAGE-GROUP
                          NEXTPAGE-TEXT
                          PARTY-TEXT
                          CANDIDATE-TEXT
                          RACE-TEXT
                          BUTTON-GROUP)
              (ADD-DM (VOTE ISA
                            MAKEVOTE
                            STATE
                            START-VOTING
                            TO-DO
                            SELECTCANDIDATE
                            DEFAULT
                            "party3"
                            ENDSTATE
                            "nameofrace"
                            LEFT
                            -1
                            RIGHT
                            -1)
                      (CANDIDATE1 ISA CANDIDATE NAME "candidate1"
                       PARTY "party2" RACE "temporaryracename0")
                      (CANDIDATE4 ISA CANDIDATE NAME "candidate4"
                       PARTY "party2" RACE "temporaryracename1")
                      (CANDIDATE7 ISA CANDIDATE NAME "candidate7"
                       PARTY "party2" RACE "temporaryracename2")
                      (CANDIDATE10 ISA CANDIDATE NAME "candidate10"
                       PARTY "party3" RACE "temporaryracename3")
                      (CANDIDATE13 ISA CANDIDATE NAME "candidate13"
                       PARTY "party1" RACE "temporaryracename4")
                      (CANDIDATE16 ISA CANDIDATE NAME "candidate16"
                       PARTY "party1" RACE "temporaryracename5")
                      (CANDIDATE19 ISA CANDIDATE NAME "candidate19"
                       PARTY "party2" RACE "temporaryracename6")
                      (CANDIDATE21 ISA CANDIDATE NAME "candidate21")
                      (CANDIDATE24 ISA CANDIDATE NAME "candidate24")
                      (CANDIDATE29 ISA CANDIDATE NAME "candidate29")
                      (TEMPORARYRACENAME13 ISA ABSTAIN CONTEST
                       "temporaryracename13")
                      (TEMPORARYRACENAME14 ISA ABSTAIN CONTEST
                       "temporaryracename14")
                      (TEMPORARYRACENAME15 ISA ABSTAIN CONTEST
                       "temporaryracename15")
                      (TEMPORARYRACENAME16 ISA ABSTAIN CONTEST
                       "temporaryracename16")
                      (TEMPORARYRACENAME17 ISA ABSTAIN CONTEST
                       "temporaryracename17"))
              (P FIND-FIRST-RACE
                 =GOAL>
                 STATE
                 START-VOTING
                 LEFT
                 =LEFT-BOUND
                 ==>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 >
                 SCREEN-X
                 =LEFT-BOUND
                 <
                 SCREEN-X
                 150
                 SCREEN-Y
                 LOWEST
                 =GOAL>
                 STATE
                 ATTENDING-RACE-NEXT-COLUMN
                 RIGHT
                 -1)
              (P FIND-RACE-SAME-COLUMN
                 =GOAL>
                 STATE
                 FIND-NEXT-RACE
                 LEFT
                 =LEFT-BOUND
                 RIGHT
                 =RIGHT-BOUND
                 =IMAGINAL>
                 RACE-GROUP
                 =RACE-GROUP
                 CANDIDATE-GROUP
                 =CANDIDATE-GROUP
                 PARTY-GROUP
                 =PARTY-GROUP
                 ==>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 >
                 SCREEN-X
                 =LEFT-BOUND
                 <
                 SCREEN-X
                 =RIGHT-BOUND
                 >
                 SCREEN-Y
                 CURRENT
                 -
                 GROUP
                 =RACE-GROUP
                 -
                 GROUP
                 =CANDIDATE-GROUP
                 -
                 GROUP
                 =PARTY-GROUP
                 SCREEN-Y
                 LOWEST
                 KIND
                 TEXT
                 =IMAGINAL>
                 =GOAL>
                 STATE
                 ATTENDING-RACE-SAME-COLUMN
                 TO-DO
                 SELECTCANDIDATE)
              (P FIND-RACE-SAME-COLUMN-NO-MATCH
                 =GOAL>
                 STATE
                 ATTENDING-RACE-SAME-COLUMN
                 ?VISUAL-LOCATION>
                 BUFFER
                 FAILURE
                 ==>
                 =GOAL>
                 STATE
                 FIND-TOP-RACE)
              (P ATTEND-RACE-SAME-COLUMN
                 =GOAL>
                 STATE
                 ATTENDING-RACE-SAME-COLUMN
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 ?VISUAL>
                 STATE
                 FREE
                 ?IMAGINAL>
                 STATE
                 FREE
                 ==>
                 +IMAGINAL>
                 RACE-GROUP
                 NONE
                 CANDIDATE-GROUP
                 NONE
                 PARTY-GROUP
                 NONE
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =VISUAL-LOCATION>
                 =GOAL>
                 STATE
                 STORING-RACE-GROUP)
              (P FIND-TOP-RACE
                 =GOAL>
                 STATE
                 FIND-TOP-RACE
                 LEFT
                 =LEFT-BOUND
                 RIGHT
                 =RIGHT-BOUND
                 ==>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 >
                 SCREEN-X
                 =LEFT-BOUND
                 <
                 SCREEN-X
                 =RIGHT-BOUND
                 SCREEN-Y
                 LOWEST
                 KIND
                 TEXT
                 =GOAL>
                 STATE
                 ATTENDING-TOP-RACE)
              (P ATTEND-TOP-RACE
                 =GOAL>
                 STATE
                 ATTENDING-TOP-RACE
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 ?VISUAL>
                 STATE
                 FREE
                 ==>
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =GOAL>
                 STATE
                 FIND-RACE-NEXT-COLUMN)
              (P FIND-RACE-NEXT-COLUMN
                 =GOAL>
                 STATE
                 FIND-RACE-NEXT-COLUMN
                 RIGHT
                 =RIGHT-BOUND
                 =VISUAL>
                 ==>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 >
                 SCREEN-X
                 =RIGHT-BOUND
                 :NEAREST
                 CURRENT
                 =GOAL>
                 STATE
                 ATTENDING-RACE-NEXT-COLUMN)
              (P ATTEND-RACE-NEXT-COLUMN
                 =GOAL>
                 STATE
                 ATTENDING-RACE-NEXT-COLUMN
                 RIGHT
                 =OLD-RIGHT
                 ?IMAGINAL>
                 STATE
                 FREE
                 ?VISUAL>
                 STATE
                 FREE
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 ==>
                 +IMAGINAL>
                 RACE-GROUP
                 NONE
                 CANDIDATE-GROUP
                 NONE
                 PARTY-GROUP
                 NONE
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 =GOAL>
                 STATE
                 STORING-RACE-GROUP
                 LEFT
                 =OLD-RIGHT)
              (P FIND-RACE-NEXT-COLUMN-NO-MATCH
                 =GOAL>
                 STATE
                 ATTENDING-RACE-NEXT-COLUMN
                 ?VISUAL-LOCATION>
                 BUFFER
                 FAILURE
                 ==>
                 =GOAL>
                 STATE
                 END)
              (P ENCODE-RACE
                 =GOAL>
                 STATE
                 STORING-RACE-GROUP
                 LEFT
                 =LEFT-BOUND
                 =VISUAL>
                 VALUE
                 =TEXT
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 GROUP
                 =GROUP1
                 SCREEN-Y
                 =SCREEN-Y
                 =IMAGINAL>
                 RACE-GROUP
                 NONE
                 ==>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 >
                 SCREEN-Y
                 CURRENT
                 >
                 SCREEN-X
                 =LEFT-BOUND
                 <
                 SCREEN-X
                 CURRENT
                 :NEAREST
                 CURRENT
                 KIND
                 OVAL
                 =IMAGINAL>
                 RACE-GROUP
                 =GROUP1
                 =GOAL>
                 STATE
                 FIND-BUTTON-GROUP
                 RACE-TOP
                 =SCREEN-Y
                 !OUTPUT!
                 ("Example of race is: ~s" =TEXT))
              (P ATTEND-BUTTON
                 =GOAL>
                 STATE
                 FIND-BUTTON-GROUP
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 OVAL
                 ?VISUAL>
                 STATE
                 FREE
                 ==>
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =VISUAL-LOCATION>
                 =GOAL>
                 STATE
                 STORING-BUTTON-GROUP)
              (P ENCODE-BUTTON
                 =GOAL>
                 STATE
                 STORING-BUTTON-GROUP
                 LEFT
                 =LEFT-BOUND
                 RACE-TOP
                 =TOP
                 =VISUAL>
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 OVAL
                 GROUP
                 =GROUP
                 =IMAGINAL>
                 -
                 RACE-GROUP
                 NONE
                 RACE-GROUP
                 =RACE-GROUP
                 ==>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 >
                 SCREEN-X
                 =LEFT-BOUND
                 >
                 SCREEN-Y
                 =TOP
                 :NEAREST
                 CURRENT
                 -
                 GROUP
                 =RACE-GROUP
                 KIND
                 TEXT
                 =IMAGINAL>
                 =GOAL>
                 STATE
                 FIND-CANDIDATE-GROUP)
              (P ATTEND-CANDIDATE
                 =GOAL>
                 STATE
                 FIND-CANDIDATE-GROUP
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 ?VISUAL>
                 STATE
                 FREE
                 ==>
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =VISUAL-LOCATION>
                 =GOAL>
                 STATE
                 STORING-CANDIDATE-GROUP)
              (P ENCODE-CANDIDATE
                 =GOAL>
                 STATE
                 STORING-CANDIDATE-GROUP
                 RACE-TOP
                 =TOP
                 =VISUAL>
                 VALUE
                 =TEXT
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 GROUP
                 =GROUP2
                 =IMAGINAL>
                 -
                 RACE-GROUP
                 NONE
                 CANDIDATE-GROUP
                 NONE
                 RACE-GROUP
                 =RACE-GROUP
                 ==>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 GROUP
                 =GROUP2
                 >
                 SCREEN-Y
                 CURRENT
                 =IMAGINAL>
                 CANDIDATE-GROUP
                 =GROUP2
                 =GOAL>
                 STATE
                 FIND-PARTY-GROUP-PART-1
                 !OUTPUT!
                 ("Example of candidate is: ~s" =TEXT))
              (P ATTEND-DIFFERENT-CANDIDATE
                 =GOAL>
                 STATE
                 FIND-PARTY-GROUP-PART-1
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 ?VISUAL>
                 STATE
                 FREE
                 ==>
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =VISUAL-LOCATION>
                 =GOAL>
                 STATE
                 FIND-PARTY-GROUP-PART-2)
              (P FIND-PARTY
                 =GOAL>
                 STATE
                 FIND-PARTY-GROUP-PART-2
                 LEFT
                 =LEFT-BOUND
                 RACE-TOP
                 =TOP
                 =VISUAL>
                 =IMAGINAL>
                 -
                 RACE-GROUP
                 NONE
                 -
                 CANDIDATE-GROUP
                 NONE
                 CANDIDATE-GROUP
                 =CANDIDATE-GROUP
                 RACE-GROUP
                 =RACE-GROUP
                 ==>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 >
                 SCREEN-X
                 CURRENT
                 <
                 SCREEN-Y
                 CURRENT
                 >
                 SCREEN-Y
                 =TOP
                 -
                 GROUP
                 =CANDIDATE-GROUP
                 -
                 GROUP
                 =RACE-GROUP
                 :NEAREST
                 CURRENT
                 =GOAL>
                 STATE
                 FIND-PARTY-GROUP-PART-3
                 =IMAGINAL>)
              (P ATTEND-PARTY
                 =GOAL>
                 STATE
                 FIND-PARTY-GROUP-PART-3
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 WIDTH
                 =WIDTH
                 SCREEN-X
                 =MIDDLE-X
                 ?VISUAL>
                 STATE
                 FREE
                 !BIND!
                 =NEW-RIGHT
                 (+ (/ =WIDTH 2) =MIDDLE-X)
                 ==>
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =VISUAL-LOCATION>
                 =GOAL>
                 STATE
                 STORING-PARTY-GROUP
                 RIGHT
                 =NEW-RIGHT)
              (P ENCODE-PARTY
                 =GOAL>
                 STATE
                 STORING-PARTY-GROUP
                 =VISUAL>
                 VALUE
                 =TEXT
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 GROUP
                 =GROUP3
                 =IMAGINAL>
                 -
                 RACE-GROUP
                 NONE
                 -
                 CANDIDATE-GROUP
                 NONE
                 PARTY-GROUP
                 NONE
                 ==>
                 =IMAGINAL>
                 PARTY-GROUP
                 =GROUP3
                 =GOAL>
                 STATE
                 READY-TO-MAKE-CHOICE
                 +RETRIEVAL>
                 :RECENTLY-RETRIEVED
                 RESET
                 !OUTPUT!
                 ("Example of party is: ~s" =TEXT))
              (P SELECT-CHOICE_LOCATE-CONTEST-DESCRIPTION
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 READY-TO-MAKE-CHOICE
                 =IMAGINAL>
                 RACE-GROUP
                 =VAL1
                 ?VISUAL-LOCATION>
                 STATE
                 FREE
                 ==>
                 =IMAGINAL>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 GROUP
                 =VAL1
                 =GOAL>
                 STATE
                 FOUND-CONTEST-DESCRIPTION
                 !EVAL!
                 (SETF CURRENT-STRAT 'RETRIEVAL))
              (P SELECT-CHOICE_ATTEND-CONTEST-DESCRIPTION
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 FOUND-CONTEST-DESCRIPTION
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 =TEXT
                 GROUP
                 =VAL1
                 ?VISUAL>
                 STATE
                 FREE
                 ==>
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =GOAL>
                 STATE
                 ATTENDED-CONTEST-DESCRIPTION)
              (P CHECK-CONTEST
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 ATTENDED-CONTEST-DESCRIPTION
                 =VISUAL>
                 ISA
                 TEXT
                 VALUE
                 =TEXTVAL
                 ?RETRIEVAL>
                 STATE
                 FREE
                 =IMAGINAL>
                 ==>
                 +RETRIEVAL>
                 ISA
                 ABSTAIN
                 CONTEST
                 =TEXTVAL
                 =IMAGINAL>
                 ISA
                 MAKEVOTE
                 RACE
                 =TEXTVAL
                 =GOAL>
                 STATE
                 CHECKING-CONTEST)
              (P ABSTAIN
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 CHECKING-CONTEST
                 =RETRIEVAL>
                 ISA
                 ABSTAIN
                 CONTEST
                 =THIS
                 ==>
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 FIND-NEXT-RACE)
              (P SELECT-CHOICE_ENCODE-CONTEST-DESCRIPTION
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 CHECKING-CONTEST
                 ?RETRIEVAL>
                 BUFFER
                 FAILURE
                 =IMAGINAL>
                 ISA
                 MAKEVOTE
                 RACE
                 =TEXTVAL
                 ==>
                 +RETRIEVAL>
                 ISA
                 CANDIDATE
                 RACE
                 =TEXTVAL
                 =IMAGINAL>
                 =GOAL>
                 STATE
                 ENCODED-CONTEST-DESCRIPTION
                 !OUTPUT!
                 ("Contest is: ~s" =TEXTVAL))
              (P INITIAL-RETRIEVAL-SUCCESS
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 ENCODED-CONTEST-DESCRIPTION
                 =RETRIEVAL>
                 ISA
                 CANDIDATE
                 RACE
                 =R
                 NAME
                 =N
                 =IMAGINAL>
                 ==>
                 =RETRIEVAL>
                 =IMAGINAL>
                 ISA
                 MAKEVOTE
                 RACE
                 =R
                 CANDIDATE
                 =N
                 =GOAL>
                 STATE
                 SEARCH-SCREEN-RETRIEVAL
                 !OUTPUT!
                 ("I'm voting for: ~s" =N))
              (P SELECT-CHOICE_SEARCH-SCREEN-FASTEST_RETRIEVAL
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 SEARCH-SCREEN-RETRIEVAL
                 ?VISUAL-LOCATION>
                 STATE
                 FREE
                 =IMAGINAL>
                 CANDIDATE-GROUP
                 =VAL2
                 ==>
                 =IMAGINAL>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 GROUP
                 =VAL2
                 :ATTENDED
                 NIL
                 =GOAL>
                 STATE
                 SOMETHING-FOUND-RETRIEVAL)
              (P SELECT-CHOICE_ATTEND-SEARCH_RETRIEVAL
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 SOMETHING-FOUND-RETRIEVAL
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 GROUP
                 =VAL2
                 ?VISUAL>
                 STATE
                 FREE
                 ==>
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =GOAL>
                 STATE
                 ATTENDING-SOMETHING-FOUND-RETRIEVAL)
              (P SELECT-CHOICE_ENCODE-SEARCH_RETRIEVAL
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 ATTENDING-SOMETHING-FOUND-RETRIEVAL
                 =VISUAL>
                 ISA
                 TEXT
                 VALUE
                 =VAL
                 SCREEN-POS
                 =POS
                 ?VISUAL-LOCATION>
                 STATE
                 FREE
                 ==>
                 =VISUAL>
                 =GOAL>
                 STATE
                 ENCODED-SEARCH-RETRIEVAL
                 !OUTPUT!
                 ("Looking at candidate: ~s" =VAL))
              (P SELECT-CHOICE_IMAGINAL-MATCH-STOP_RETRIEVAL
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 ENCODED-SEARCH-RETRIEVAL
                 =IMAGINAL>
                 ISA
                 MAKEVOTE
                 CANDIDATE
                 =VAL
                 =VISUAL>
                 ISA
                 TEXT
                 VALUE
                 =VAL
                 SCREEN-POS
                 =POS
                 ?VISUAL-LOCATION>
                 STATE
                 FREE
                 ?MANUAL>
                 STATE
                 FREE
                 ==>
                 =IMAGINAL>
                 =VISUAL>
                 +MANUAL>
                 ISA
                 MOVE-CURSOR
                 LOC
                 =POS
                 =GOAL>
                 STATE
                 MOVED-TO-CANDIDATE)
              (P SELECT-CHOICE_NO-MATCH_RETRIEVAL
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 ENCODED-SEARCH-RETRIEVAL
                 ?VISUAL-LOCATION>
                 STATE
                 FREE
                 ==>
                 =GOAL>
                 STATE
                 SEARCH-SCREEN-RETRIEVAL)
              (P RETRIEVAL-FAILS
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 ENCODED-CONTEST-DESCRIPTION
                 ?RETRIEVAL>
                 BUFFER
                 FAILURE
                 ==>
                 =GOAL>
                 STATE
                 SEARCH-SCREEN-RECOGNITION
                 !OUTPUT!
                 ("Initial retrieval fails, switch to recog strategy.")
                 !EVAL!
                 (SETF CURRENT-STRAT 'RECOGNITION))
              (P RETRIEVAL-FAILS-AFTER-SEARCHING
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 ENCODED-SEARCH-RETRIEVAL
                 ?VISUAL-LOCATION>
                 BUFFER
                 FAILURE
                 ==>
                 =GOAL>
                 STATE
                 SEARCH-SCREEN-RECOGNITION
                 !OUTPUT!
                 ("Looked at everything and nothing retrieved--switch to recognition")
                 !EVAL!
                 (SETF CURRENT-STRAT 'RECOGNITION))
              (P SELECT-CHOICE_SEARCH-SCREEN-FASTEST_RECOGNITION
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 SEARCH-SCREEN-RECOGNITION
                 ?RETRIEVAL>
                 STATE
                 FREE
                 ?VISUAL-LOCATION>
                 STATE
                 FREE
                 ?VISUAL>
                 STATE
                 FREE
                 =IMAGINAL>
                 CANDIDATE-GROUP
                 =VAL2
                 ==>
                 =IMAGINAL>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 :ATTENDED
                 NIL
                 GROUP
                 =VAL2
                 =GOAL>
                 STATE
                 SOMETHING-FOUND-RECOGNITION)
              (P SELECT-CHOICE_ATTEND-SEARCH_RECOGNITION
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 SOMETHING-FOUND-RECOGNITION
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 GROUP
                 =VAL2
                 ?VISUAL>
                 STATE
                 FREE
                 ==>
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =GOAL>
                 STATE
                 ATTENDING-SOMETHING-FOUND-RECOGNITION)
              (P SELECT-CHOICE_ENCODE-SEARCH_RECOGNITION
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 ATTENDING-SOMETHING-FOUND-RECOGNITION
                 =VISUAL>
                 ISA
                 TEXT
                 VALUE
                 =VAL
                 ?VISUAL-LOCATION>
                 STATE
                 FREE
                 ?RETRIEVAL>
                 STATE
                 FREE
                 ==>
                 =VISUAL>
                 +RETRIEVAL>
                 ISA
                 CANDIDATE
                 NAME
                 =VAL
                 =GOAL>
                 STATE
                 ENCODED-SEARCH-RECOGNITION
                 !OUTPUT!
                 ("Looking at Candidate: ~s" =VAL))
              (P SELECT-CHOICE_MATCH-STOP_RECOGNITION
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 ENCODED-SEARCH-RECOGNITION
                 =RETRIEVAL>
                 ISA
                 CANDIDATE
                 NAME
                 =VAL
                 =VISUAL>
                 ISA
                 TEXT
                 VALUE
                 =VAL
                 SCREEN-POS
                 =POS
                 ?VISUAL-LOCATION>
                 STATE
                 FREE
                 ?MANUAL>
                 STATE
                 FREE
                 ==>
                 =RETRIEVAL>
                 =VISUAL>
                 +MANUAL>
                 ISA
                 MOVE-CURSOR
                 LOC
                 =POS
                 =GOAL>
                 STATE
                 MOVED-TO-CANDIDATE
                 !OUTPUT!
                 ("Match! Voting for: ~s" =VAL))
              (P SELECT-CHOICE_NO-MATCH_RECOGNITION
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 ENCODED-SEARCH-RECOGNITION
                 ?VISUAL-LOCATION>
                 STATE
                 FREE
                 ?RETRIEVAL>
                 BUFFER
                 FAILURE
                 ==>
                 =RETRIEVAL>
                 =GOAL>
                 STATE
                 SEARCH-SCREEN-RECOGNITION
                 !OUTPUT!
                 ("Name does not match. Read another."))
              (P RECOGNITION-FAILS
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 SOMETHING-FOUND-RECOGNITION
                 ?VISUAL-LOCATION>
                 BUFFER
                 FAILURE
                 ==>
                 =GOAL>
                 STATE
                 SEARCH-BY-PARTY
                 !OUTPUT!
                 ("Looked at everything and nothing retrieved-- voting by party")
                 !EVAL!
                 (SETF CURRENT-STRAT 'PARTY))
              (P VBP-SELECT-CHOICE_SEARCH-SCREEN-RANDOM
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 SEARCH-BY-PARTY
                 ?RETRIEVAL>
                 STATE
                 FREE
                 ?VISUAL-LOCATION>
                 STATE
                 FREE
                 =IMAGINAL>
                 PARTY-GROUP
                 =VAL3
                 ==>
                 =IMAGINAL>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 GROUP
                 =VAL3
                 :ATTENDED
                 NIL
                 =GOAL>
                 STATE
                 VBP-ATTEND-NAME)
              (P VOTE-BY-PARTY_ATTEND-LOCATION
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 VBP-ATTEND-NAME
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 TEXT
                 GROUP
                 =VAL3
                 ?VISUAL>
                 STATE
                 FREE
                 ==>
                 +VISUAL>
                 ISA
                 MOVE-ATTENTION
                 SCREEN-POS
                 =VISUAL-LOCATION
                 =GOAL>
                 STATE
                 PARTY-FOUND)
              (P VOTE-BY-PARTY_MATCH
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 PARTY-FOUND
                 DEFAULT
                 =PARTY
                 =VISUAL>
                 ISA
                 TEXT
                 VALUE
                 =PARTY
                 SCREEN-POS
                 =POS
                 ?MANUAL>
                 STATE
                 FREE
                 ==>
                 =VISUAL>
                 +MANUAL>
                 ISA
                 MOVE-CURSOR
                 LOC
                 =POS
                 =GOAL>
                 STATE
                 MOVED-TO-CANDIDATE
                 !OUTPUT!
                 ("Party found ~s and matches default" =PARTY))
              (P VOTE-BY-PARTY_NO-MATCH
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 PARTY-FOUND
                 DEFAULT
                 =P
                 =VISUAL>
                 ISA
                 TEXT
                 -
                 VALUE
                 =P
                 VALUE
                 =Q
                 ==>
                 =GOAL>
                 STATE
                 SEARCH-BY-PARTY
                 !OUTPUT!
                 ("Party ~s does not match default, search again"
                  =Q))
              (P VOTE-BY-PARTY_NO-MATCH-ABSTAIN
                 =GOAL>
                 ISA
                 MAKEVOTE
                 STATE
                 VBP-ATTEND-NAME
                 ?VISUAL-LOCATION>
                 BUFFER
                 FAILURE
                 ==>
                 =GOAL>
                 STATE
                 FIND-NEXT-RACE)
              (SPP SELECT-CHOICE_IMAGINAL-MATCH-STOP_RETRIEVAL
                   :U
                   1000)
              (SPP SELECT-CHOICE_SEARCH-SCREEN-FASTEST_RETRIEVAL
                   :U
                   8)
              (SPP SELECT-CHOICE_SEARCH-SCREEN-FASTEST_RECOGNITION
                   :U
                   8)
              (SPP CHECK-CONTEST :U 4000)
              (P FIND-BUBBLE
                 =GOAL>
                 STATE
                 MOVED-TO-CANDIDATE
                 LEFT
                 =LEFT-BOUND
                 RIGHT
                 =RIGHT-BOUND
                 ==>
                 +VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 OVAL
                 >
                 SCREEN-X
                 =LEFT-BOUND
                 <
                 SCREEN-X
                 =RIGHT-BOUND
                 :NEAREST
                 CURRENT
                 =GOAL>
                 STATE
                 ATTENDING-BUBBLE)
              (P MOVE-MOUSE-TO-BUBBLE
                 =GOAL>
                 STATE
                 ATTENDING-BUBBLE
                 ?MANUAL>
                 STATE
                 FREE
                 =VISUAL-LOCATION>
                 ISA
                 VISUAL-LOCATION
                 KIND
                 OVAL
                 ==>
                 +MANUAL>
                 ISA
                 MOVE-CURSOR
                 LOC
                 =VISUAL-LOCATION
                 =GOAL>
                 STATE
                 MOVING-MOUSE-TO-BUBBLE)
              (P CLICK-BUBBLE
                 =GOAL>
                 STATE
                 MOVING-MOUSE-TO-BUBBLE
                 ?MANUAL>
                 STATE
                 FREE
                 ==>
                 +MANUAL>
                 ISA
                 CLICK-MOUSE
                 =GOAL>
                 STATE
                 FIND-NEXT-RACE)
              (GOAL-FOCUS VOTE))